using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(Light))]
public class FlickeringLight : MonoBehaviour
{
    private Light lightToFlicker;

    [SerializeField, Range(0f, 3f)]
    private float minIntensity = 0.5f;

    [SerializeField, Range(0f, 3f)]
    private float maxIntensity = 1.2f;

    [SerializeField, Min(0f)]
    private float timeBetweenIntensity = 0.1f;

    private float currentTimer;

    private void Awake()
    {
        if (lightToFlicker == null)
            lightToFlicker = GetComponent<Light>();

        ValidateIntensityBounds();
    }

    private void Update()
    {
        currentTimer += Time.deltaTime;

        if (currentTimer >= timeBetweenIntensity)
        {
            lightToFlicker.intensity = Random.Range(minIntensity, maxIntensity);
            currentTimer = 0f;
        }
    }

    private void ValidateIntensityBounds()
    {
        if (minIntensity > maxIntensity)
        {
            Debug.LogWarning("Min intensity is greater than max intensity YOU SUUUUCKKKK!");
            (minIntensity, maxIntensity) = (maxIntensity, minIntensity);
        }
    }
}
